Feature/backend/outer id strings
Cofinpro/bootcamp-2022-11 pull request #14
Opened 2022-12-31 15:29 UTC by l-rehm

Fixed all new integration tests and unit tests to work with outer IDs now.

2022-12-31 17:51 UTC, MarkusKremerr commented
Frontend funktioniert nicht mehr. wenn man profil anschauen will wird profil mit der Id NaN per axios angefragt.
Fix wäre relativ einfach den datentyp der Id im Frontend von number auf String zu ändern.

2022-12-31 17:51 UTC, MarkusKremerr requested changes
Frontend funktioniert nicht mehr. wenn man profil anschauen will wird profil mit der Id NaN per axios angefragt.
Fix wäre relativ einfach den datentyp der Id im Frontend von number auf String zu ändern.

2022-12-31 19:12 UTC, l-rehm commented
Keine Ahnung vom Frontend. Hab nur Backend getestet. Müsste sich einer von den Gurus mal anschauen. Guten Rutsch!
________________________________
Von: MarkusKremerr ***@***.***>
Gesendet: Saturday, December 31, 2022 6:51:18 PM
An: Cofinpro/bootcamp-2022-11 ***@***.***>
Cc: Lennart Rehmer ***@***.***>; Author ***@***.***>
Betreff: Re: [Cofinpro/bootcamp-2022-11] Feature/backend/outer id strings (PR #14)


Frontend funktioniert nicht mehr. wenn man profil anschauen will wird profil mit der Id NaN per axios angefragt.
Fix wäre relativ einfach den datentyp der Id im Frontend von number auf String zu ändern.

—
Reply to this email directly, view it on GitHub<https://github.com/Cofinpro/bootcamp-2022-11/pull/14#issuecomment-1368258376>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/A4BQPYWQVXIJB2CYW6EJXBLWQBXBNANCNFSM6AAAAAATNTDKP4>.
You are receiving this because you authored the thread.Message ID: ***@***.***>

2023-01-04 09:54 UTC, MarkusKremerr approved these changes

2023-01-04 09:54 UTC, merged